import pandas as pd

# This file is required due to the number of players with identical names, this dataframe was constructed manually
# to complete the bbref codes for each player

if __name__ == "__main__":

    columns = ["first_name", "last_name", "From", "To", "bbref"]
    duplicate_df = pd.DataFrame(columns=columns)

    duplicate_df.loc[len(duplicate_df.index)] = ["Dan", "Anderson", "1968", "1969", "a/anderda02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Bill", "Bradley", "1968", "1968", "b/bradlbi02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Dee", "Brown", "2007", "2009", "b/brownde03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Roger", "Brown", "1973", "1980", "b/brownro02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mark", "Davis", "1996", "2000", "d/davisma02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mike", "Davis", "1983", "1983", "d/davismi03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Johnny", "Davis", "2023", "2023", "d/davisjo06"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Bob", "Duffy", "1963", "1965", "d/duffybo02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mike", "Dunleavy", "2003", "2017", "d/dunlemi02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Patrick", "Ewing", "2011", "2011", "e/ewingpa02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Matt", "Guokas", "1967", "1976", "g/guokama02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Gerald", "Henderson", "2010", "2017", "h/hendege02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Cedric", "Henderson", "1998", "2002", "h/hendece02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Luke", "Jackson", "2005", "2008", "j/jackslu02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Tony", "Jackson", "1981", "1981", "j/jacksto02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mike", "James", "2018", "2021", "j/jamesmi02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["George", "Johnson", "1973", "1986", "j/johnsge02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["George", "Johnson", "1979", "1986", "j/johnsge03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Chris", "Johnson", "2011", "2013", "j/johnsch03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Chris", "Johnson", "2013", "2016", "j/johnsch04"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Eddie", "Johnson", "1978", "1987", "j/johnsed02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Eddie", "Johnson", "1982", "1999", "j/johnsed03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Larry", "Johnson", "1992", "2001", "j/johnsla02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Ken", "Johnson", "2003", "2003", "j/johnske03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Charles", "Jones", "1985", "1989", "j/jonesch02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Charles", "Jones", "1999", "2000", "j/jonesch03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Bobby", "Jones", "2007", "2008", "j/jonesbo02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mark", "Jones", "1984", "1984", "j/jonesma02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Mark", "Jones", "2005", "2005", "j/jonesma03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["George", "King", "2019", "2022", "k/kingge03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Freddie", "Lewis", "1967", "1977", "l/lewisfr02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Jim", "Paxson", "1980", "1990", "p/paxsoji02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Walker", "Russell", "2012", "2012", "r/russewa02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Charles", "Smith", "1990", "1996", "s/smithch02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Charles", "Smith", "1998", "2996", "s/smithch04"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Michael", "Smith", "1995", "2001", "s/smithmi02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Don", "Smith", "1975", "1975", "s/smithdo02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Greg", "Smith", "2012", "2016", "s/smithgr02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Sam", "Smith", "1979", "1980", "s/smithsa02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Chris", "Smith", "1993", "1995", "s/smithch03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Chris", "Smith", "2014", "2014", "s/smithch05"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Jeff", "Taylor", "2013", "2015", "t/tayloje03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Jack", "Turner", "1962", "1962", "t/turneja02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["David", "Vaughn", "1996", "1999", "v/vaughda02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Marcus", "Williams", "2007", "2010", "w/willima03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Marcus", "Williams", "2008", "2009", "w/willima04"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Sam", "Williams", "1982", "1985", "w/willisa02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Reggie", "Williams", "2010", "2017", "w/willire02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Brandon", "Williams", "2022", "2022", "w/willibr03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Bobby", "Wilson", "1968", "1968", "w/wilsobo02"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Bobby", "Wilson", "1975", "1978", "w/wilsobo03"]
    duplicate_df.loc[len(duplicate_df.index)] = ["Chris", "Wright", "2013", "2013", "w/wrighch02"]

    duplicate_df.to_csv("~/github/nba_data_scraper/src/raw_data/duplicate_names.csv")
